# Site settings
title: Roshan's Projects & Blogs
description: Details of my projects and blogs
author: Roshan

# Build settings
theme: simply-jekyll
remote_theme: abhinav/simply-jekyll

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# URL settings
url: "https://roshantechlearn.github.io"
baseurl: ""

# Permalink structure
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
